/* Deterministic offline 4/8/12-week periodization in all supported languages. */
(function(){
  "use strict";
  const copy={
    pt:{title:"Plano progressivo de {weeks} semanas — {days} dias por semana",goal:"Objetivo: {goal}. Sessões de aproximadamente {duration} minutos. Equipamento: {equipment}.",week:"Semana",phases:["adaptação e técnica","recuperação e consolidação","progressão de repetições","sobrecarga controlada","consolidação final"],instructions:["Registre cargas e termine com 2–3 repetições em reserva.","Acrescente uma repetição por série quando a técnica estiver estável.","Ao completar a faixa, aumente a carga em 2–5%.","Reduza 30–40% das séries e evite a falha."],footer:"Distribua estímulos do mesmo grupo muscular com cerca de 48 horas quando possível. Se perder uma sessão, continue a sequência sem dobrar o treino. Dor aguda, queda persistente de desempenho ou recuperação ruim exigem redução de carga e avaliação adequada.",missed:"Ajuste por sessão perdida: não compense com dois treinos completos no mesmo dia; retome pelo próximo treino da sequência.",goals:{loss:"emagrecimento com preservação muscular",muscle:"hipertrofia",general:"força e condicionamento"}},
    en:{title:"Progressive {weeks}-week plan — {days} days per week",goal:"Goal: {goal}. Sessions of approximately {duration} minutes. Equipment: {equipment}.",week:"Week",phases:["adaptation and technique","recovery and consolidation","repetition progression","controlled overload","final consolidation"],instructions:["Log loads and finish with 2–3 repetitions in reserve.","Add one repetition per set when technique is stable.","After reaching the top of the range, increase load by 2–5%.","Reduce sets by 30–40% and avoid failure."],footer:"Allow about 48 hours between demanding sessions for the same muscle group when possible. If you miss a session, resume the sequence without doubling workouts. Acute pain, persistent performance decline, or poor recovery requires load reduction and appropriate assessment.",missed:"Missed-session adjustment: do not compensate with two full workouts on the same day; resume with the next session in sequence.",goals:{loss:"fat loss while preserving muscle",muscle:"muscle gain",general:"strength and conditioning"}},
    es:{title:"Plan progresivo de {weeks} semanas — {days} días por semana",goal:"Objetivo: {goal}. Sesiones de aproximadamente {duration} minutos. Equipo: {equipment}.",week:"Semana",phases:["adaptación y técnica","recuperación y consolidación","progresión de repeticiones","sobrecarga controlada","consolidación final"],instructions:["Registra las cargas y termina con 2–3 repeticiones en reserva.","Añade una repetición por serie cuando la técnica sea estable.","Al completar el rango, aumenta la carga un 2–5%.","Reduce las series un 30–40% y evita el fallo."],footer:"Deja unas 48 horas entre estímulos exigentes del mismo grupo muscular cuando sea posible. Si pierdes una sesión, continúa la secuencia sin duplicar entrenamientos. Dolor agudo o recuperación deficiente exige reducir la carga y buscar evaluación adecuada.",missed:"Ajuste por sesión perdida: no compenses con dos entrenamientos completos el mismo día; retoma la siguiente sesión de la secuencia.",goals:{loss:"pérdida de grasa preservando músculo",muscle:"hipertrofia",general:"fuerza y acondicionamiento"}},
    de:{title:"Progressiver {weeks}-Wochen-Plan — {days} Tage pro Woche",goal:"Ziel: {goal}. Einheiten von ungefähr {duration} Minuten. Ausrüstung: {equipment}.",week:"Woche",phases:["Anpassung und Technik","Erholung und Festigung","Wiederholungsprogression","kontrollierte Steigerung","abschließende Festigung"],instructions:["Gewichte notieren und mit 2–3 Wiederholungen in Reserve beenden.","Bei stabiler Technik eine Wiederholung pro Satz ergänzen.","Am oberen Ende des Bereichs das Gewicht um 2–5 % erhöhen.","Sätze um 30–40 % reduzieren und Muskelversagen vermeiden."],footer:"Zwischen anspruchsvollen Reizen derselben Muskelgruppe möglichst etwa 48 Stunden lassen. Nach einer verpassten Einheit die Reihenfolge fortsetzen, ohne Training zu verdoppeln. Akute Schmerzen oder anhaltend schlechte Erholung erfordern Belastungsreduktion und fachliche Abklärung.",missed:"Anpassung nach verpasster Einheit: nicht mit zwei vollständigen Einheiten am selben Tag kompensieren, sondern die Reihenfolge fortsetzen.",goals:{loss:"Fettabbau bei Muskelerhalt",muscle:"Muskelaufbau",general:"Kraft und Kondition"}}
  };
  const fill=(value,data)=>value.replace(/\{(\w+)\}/g,(_,key)=>data[key]);
  function build({weeks=4,days=3,durationMinutes=45,goal="general",equipment="bodyweight",language="pt"}={}){
    weeks=[4,8,12].includes(Number(weeks))?Number(weeks):4;days=Math.max(2,Math.min(6,Number(days)||3));language=copy[language]?language:"pt";
    const c=copy[language],phases=[];
    for(let week=1;week<=weeks;week+=1){const recovery=week%4===0,phaseIndex=week<=2?0:recovery?1:week<=6?2:week<=10?3:4,instructionIndex=recovery?3:week%4===2?1:week%4===3?2:0;phases.push({week,phase:c.phases[phaseIndex],recovery,volumeFactor:recovery?.65:1,intensity:recovery?"light":week%4===3?"moderate-high":"moderate",instruction:c.instructions[instructionIndex]});}
    const data={weeks,days,duration:durationMinutes,goal:c.goals[goal]||goal,equipment};
    const text=`${fill(c.title,data)}\n${fill(c.goal,data)}\n\n${phases.map(p=>`• ${c.week} ${p.week} — ${p.phase}: ${p.instruction}`).join("\n")}\n\n${c.footer}`;
    return {type:"periodized-workout",topic:"weekly-workout",weeks,days,durationMinutes,goal,equipment,language,phases,text,version:"2026.08.2"};
  }
  function adapt(plan,{missedDay,newDays,newDuration}={}){const next=build({...plan,days:newDays||plan.days,durationMinutes:newDuration||plan.durationMinutes});if(missedDay)next.text=`${copy[next.language].missed}\n\n${next.text}`;return next;}
  window.FitnessPeriodizationEngine={build,adapt};
})();

